package ru.familybudget.app

import android.os.Bundle
import androidx.activity.ComponentActivity
import androidx.activity.compose.setContent
import androidx.compose.foundation.background
import androidx.compose.foundation.layout.*
import androidx.compose.foundation.lazy.LazyColumn
import androidx.compose.foundation.lazy.items
import androidx.compose.foundation.shape.RoundedCornerShape
import androidx.compose.material.icons.Icons
import androidx.compose.material.icons.rounded.*
import androidx.compose.material3.*
import androidx.compose.runtime.*
import androidx.compose.ui.Alignment
import androidx.compose.ui.Modifier
import androidx.compose.ui.graphics.Color
import androidx.compose.ui.text.font.FontWeight
import androidx.compose.ui.unit.dp
import androidx.compose.ui.unit.sp

data class Op(val title:String,val amount:Double,val income:Boolean,val account:String)
enum class Tab(val title:String){HOME("Главная"),OPS("Операции"),BUDGET("Бюджет"),ANALYTICS("Аналитика"),MORE("Ещё")}
private val Y=Color(0xFFFFDD2D); private val G=Color(0xFF8A8F98)
class MainActivity:ComponentActivity(){override fun onCreate(b:Bundle?){super.onCreate(b);setContent{App()}}}
@Composable fun App(){var dark by remember{mutableStateOf(false)};var tab by remember{mutableStateOf(Tab.HOME)};var add by remember{mutableStateOf(false)};var settings by remember{mutableStateOf(false)};val ops=remember{mutableStateListOf<Op>()};MaterialTheme(if(dark)darkColorScheme(primary=Y,background=Color(0xFF111111),surface=Color(0xFF1B1B1B)) else lightColorScheme(primary=Color(0xFF111111),background=Color(0xFFF6F6F6),surface=Color.White)){Scaffold(topBar={TopAppBar({Column{Text("Семейный бюджет",fontWeight=FontWeight.Bold);Text("8.1 PRO • smart finance",fontSize=11.sp,color=MaterialTheme.colorScheme.onSurfaceVariant)}},{IconButton({settings=true}){Icon(Icons.Rounded.Settings,"Настройки")}})},bottomBar={NavigationBar{Tab.values().forEach{t->NavigationBarItem(t==tab,{tab=t},{Icon(icon(t),t.title)},{Text(t.title,fontSize=10.sp)})}}},floatingActionButton={if(tab==Tab.HOME||tab==Tab.OPS)FloatingActionButton({add=true},containerColor=Y,contentColor=Color.Black){Icon(Icons.Rounded.Add,"Добавить")}}){p->Box(Modifier.fillMaxSize().padding(p)){when(tab){Tab.HOME->Home(ops);Tab.OPS->OpsPage(ops);Tab.BUDGET->Budget();Tab.ANALYTICS->Analytics(ops);Tab.MORE->More{settings=true}}}};if(add)Add({add=false}){ops.add(it);add=false};if(settings)Settings(dark,{dark=it},{settings=false})}}
fun icon(t:Tab)=when(t){Tab.HOME->Icons.Rounded.Home;Tab.OPS->Icons.Rounded.Payments;Tab.BUDGET->Icons.Rounded.Savings;Tab.ANALYTICS->Icons.Rounded.Analytics;Tab.MORE->Icons.Rounded.MoreHoriz}
@Composable fun Page(c:@Composable ColumnScope.()->Unit)=Column(Modifier.fillMaxSize().background(MaterialTheme.colorScheme.background).padding(16.dp),content=c)
@Composable fun Home(ops:List<Op>){val i=ops.filter{it.income}.sumOf{it.amount};val e=ops.filter{!it.income}.sumOf{it.amount};Page{Text("ОБЗОР",fontWeight=FontWeight.Bold,color=MaterialTheme.colorScheme.onSurfaceVariant);Spacer(Modifier.height(8.dp));Card(Modifier.fillMaxWidth(),RoundedCornerShape(24.dp),colors=CardDefaults.cardColors(Y)){Column(Modifier.padding(22.dp)){Text("ОБЩИЙ БАЛАНС",fontSize=12.sp,color=Color.Black.copy(.6f));Text("%.0f ₽".format(i-e),fontSize=34.sp,fontWeight=FontWeight.Bold,color=Color.Black);Row(Modifier.fillMaxWidth(),Arrangement.SpaceBetween){Text("Доходы %.0f ₽".format(i),color=Color.Black);Text("Расходы %.0f ₽".format(e),color=Color.Black)}}};Spacer(Modifier.height(14.dp));Text("СЧЕТА",fontWeight=FontWeight.Bold,color=MaterialTheme.colorScheme.onSurfaceVariant);listOf("Яндекс","ОЗОН","Сбербанк","Т-Банк","Кредитка").forEach{Account(it)};Text("ПОСЛЕДНИЕ ОПЕРАЦИИ",fontWeight=FontWeight.Bold,color=MaterialTheme.colorScheme.onSurfaceVariant);if(ops.isEmpty())Empty("Пока нет операций","Нажмите +, чтобы добавить первую")else ops.takeLast(4).reversed().forEach{RowOp(it)}}}
@Composable fun Account(n:String)=Card(Modifier.fillMaxWidth().padding(vertical=3.dp),RoundedCornerShape(17.dp)){Row(Modifier.padding(12.dp),verticalAlignment=Alignment.CenterVertically){Icon(Icons.Rounded.CreditCard,null);Spacer(Modifier.width(10.dp));Text(n,Modifier.weight(1f),fontWeight=FontWeight.SemiBold);Text("0 ₽",fontWeight=FontWeight.Bold)}}
@Composable fun OpsPage(ops:List<Op>)=Page{Text("ОПЕРАЦИИ",fontSize=24.sp,fontWeight=FontWeight.Bold);if(ops.isEmpty())Empty("Операций пока нет","Добавьте доход или расход")else LazyColumn{items(ops.reversed()){RowOp(it)}}}
@Composable fun RowOp(o:Op)=Row(Modifier.fillMaxWidth().padding(vertical=8.dp),verticalAlignment=Alignment.CenterVertically){Icon(if(o.income)Icons.Rounded.ArrowUpward else Icons.Rounded.ArrowDownward,null);Spacer(Modifier.width(10.dp));Column(Modifier.weight(1f)){Text(o.title,fontWeight=FontWeight.SemiBold);Text(o.account,fontSize=12.sp,color=MaterialTheme.colorScheme.onSurfaceVariant)};Text((if(o.income)"+" else "−")+"%.0f ₽".format(o.amount),fontWeight=FontWeight.Bold)}
@Composable fun Budget()=Page{Text("БЮДЖЕТ",fontSize=24.sp,fontWeight=FontWeight.Bold);Text("ПЛАНИРУЙТЕ РАСХОДЫ И КОНТРОЛИРУЙТЕ ЛИМИТЫ",fontSize=11.sp,color=MaterialTheme.colorScheme.onSurfaceVariant);listOf("ПРОДУКТЫ" to .42f,"ТРАНСПОРТ" to .27f,"ЖИЛЬЁ" to .70f,"РАЗВЛЕЧЕНИЯ" to .18f).forEach{(n,p)->Card(Modifier.fillMaxWidth().padding(vertical=5.dp),RoundedCornerShape(18.dp)){Column(Modifier.padding(15.dp)){Text(n,fontWeight=FontWeight.Bold);Spacer(Modifier.height(8.dp));LinearProgressIndicator({p},Modifier.fillMaxWidth(),color=G)}}}}
@Composable fun Analytics(ops:List<Op>)=Page{Text("АНАЛИТИКА",fontSize=24.sp,fontWeight=FontWeight.Bold);Spacer(Modifier.height(12.dp));Card(Modifier.fillMaxWidth(),RoundedCornerShape(20.dp)){Column(Modifier.padding(18.dp)){Text("РАСХОДЫ ПО МЕСЯЦАМ",fontWeight=FontWeight.Bold);Spacer(Modifier.height(20.dp));Row(Modifier.fillMaxWidth().height(140.dp),Arrangement.SpaceEvenly,Alignment.Bottom){listOf(.3f,.5f,.4f,.7f,.55f,.8f).forEach{Box(Modifier.width(28.dp).height((120*it).dp).background(G,RoundedCornerShape(7.dp)))}};HorizontalDivider(Modifier.padding(vertical=12.dp));Text("ВСЕГО РАСХОДОВ: %.0f ₽".format(ops.filter{!it.income}.sumOf{it.amount}),fontWeight=FontWeight.Bold)}}}
@Composable fun More(open:()->Unit)=Page{Text("ЕЩЁ",fontSize=24.sp,fontWeight=FontWeight.Bold);listOf("Регулярные платежи","Финансовые цели","Долги и кредиты","Календарь","Отчёты","Экспорт данных").forEach{Card(Modifier.fillMaxWidth().padding(4.dp),RoundedCornerShape(17.dp)){Text(it,Modifier.padding(16.dp))}};Button(open,Modifier.fillMaxWidth()){Text("НАСТРОЙКИ")}}
@Composable fun Empty(a:String,b:String)=Column(Modifier.fillMaxWidth().padding(top=50.dp),horizontalAlignment=Alignment.CenterHorizontally){Icon(Icons.Rounded.Payments,null,Modifier.size(46.dp));Text(a,fontWeight=FontWeight.Bold);Text(b,fontSize=12.sp,color=MaterialTheme.colorScheme.onSurfaceVariant)}
@Composable fun Add(close:()->Unit,save:(Op)->Unit){var n by remember{mutableStateOf("")};var a by remember{mutableStateOf("")};var inc by remember{mutableStateOf(false)};var acc by remember{mutableStateOf("Т-Банк")};AlertDialog(onDismissRequest=close,title={Text("НОВАЯ ОПЕРАЦИЯ")},text={Column{OutlinedTextField(n,{n=it},label={Text("Название")});OutlinedTextField(a,{a=it},label={Text("Сумма")});Row{FilterChip(inc,{inc=true},label={Text("Доход")});FilterChip(!inc,{inc=false},label={Text("Расход")})};Text("СЧЁТ");Row{listOf("Яндекс","ОЗОН","Сбербанк","Т-Банк","Кредитка").forEach{AssistChip({acc=it},{Text(it)})}}}},confirmButton={Button({val x=a.replace(',','.').toDoubleOrNull()?:0.0;if(n.isNotBlank()&&x>0)save(Op(n,x,inc,acc))}){Text("СОХРАНИТЬ")}},dismissButton={TextButton(close){Text("ОТМЕНА")}})}
@Composable fun Settings(d:Boolean,set:(Boolean)->Unit,close:()->Unit)=AlertDialog(onDismissRequest=close,title={Text("НАСТРОЙКИ")},text={Row(verticalAlignment=Alignment.CenterVertically){Text("Тёмная тема",Modifier.weight(1f));Switch(d,set)}},confirmButton={TextButton(close){Text("ГОТОВО")}})
